{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.kafka",
    "module": "spring-kafka",
    "version": "3.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.11"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.3.2.jar",
          "url": "spring-kafka-3.3.2.jar",
          "size": 874603,
          "sha512": "62b26f0b4511b81529a422920846c9bca455693c41550a96a5cd2382a8ff94c5974ed34deea00da8f0adb78c5c55d0a85b55cf4172f63c4aaac4f93b1d05f5d9",
          "sha256": "39aedad4ed809a5d0a81c00c543afc2d931201e02d5b3f0e8bc9d36591993282",
          "sha1": "2ab3df68531166d0f94bfc68380a9ce9dc4e9ca3",
          "md5": "75e970b44a65e740565c814558f12fd0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-messaging",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.2.2"
          }
        },
        {
          "group": "org.springframework.retry",
          "module": "spring-retry",
          "version": {
            "requires": "2.0.11"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-clients",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-observation",
          "version": {
            "requires": "1.14.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.3.2.jar",
          "url": "spring-kafka-3.3.2.jar",
          "size": 874603,
          "sha512": "62b26f0b4511b81529a422920846c9bca455693c41550a96a5cd2382a8ff94c5974ed34deea00da8f0adb78c5c55d0a85b55cf4172f63c4aaac4f93b1d05f5d9",
          "sha256": "39aedad4ed809a5d0a81c00c543afc2d931201e02d5b3f0e8bc9d36591993282",
          "sha1": "2ab3df68531166d0f94bfc68380a9ce9dc4e9ca3",
          "md5": "75e970b44a65e740565c814558f12fd0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-kafka-3.3.2-javadoc.jar",
          "url": "spring-kafka-3.3.2-javadoc.jar",
          "size": 1644288,
          "sha512": "90e7812c32bc629dbc1c93386be6c305d89f6502070750f348483738c31f336efbd795baaa219b6d5ae1dd241f2f9c191a228a2dd9a26fdc74117cf1dac5a174",
          "sha256": "f04dd663d1b68e58f1c17a540eb34ef9561ab8e34e1fcaf9ffa30d1de9310b84",
          "sha1": "70dcc34655564df575f8f614e91d2ae6f83b6c1a",
          "md5": "02871f6d1e15f63a04fa2409b6e958eb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-kafka-3.3.2-sources.jar",
          "url": "spring-kafka-3.3.2-sources.jar",
          "size": 584305,
          "sha512": "5c43bbddb7a0fa2142cf82b8d7d06037de7eead96ed2c3c2aecd1b2fdb7ced24aae72bf7c7a3be9b852f45038ea61244bf2971517151c1ea778358e716218c83",
          "sha256": "19cf3fad28d048873c837ca75c768961e96a4d4fc3c5b4a99ebface93dd5901b",
          "sha1": "5a8e2593a8236e899f94d78dd4e11bf6dda32778",
          "md5": "3056b490a3154dde8d26989687ac0305"
        }
      ]
    },
    {
      "name": "optionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.4.2"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "io.projectreactor.kafka",
          "module": "reactor-kafka",
          "version": {
            "requires": "1.3.23"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.3.2.jar",
          "url": "spring-kafka-3.3.2.jar",
          "size": 874603,
          "sha512": "62b26f0b4511b81529a422920846c9bca455693c41550a96a5cd2382a8ff94c5974ed34deea00da8f0adb78c5c55d0a85b55cf4172f63c4aaac4f93b1d05f5d9",
          "sha256": "39aedad4ed809a5d0a81c00c543afc2d931201e02d5b3f0e8bc9d36591993282",
          "sha1": "2ab3df68531166d0f94bfc68380a9ce9dc4e9ca3",
          "md5": "75e970b44a65e740565c814558f12fd0"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.kafka",
          "name": "spring-kafka-optional",
          "version": "3.3.2"
        }
      ]
    },
    {
      "name": "optionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.25.3"
          }
        },
        {
          "group": "org.apache.kafka",
          "module": "kafka-streams",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-reactor",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-joda",
          "version": {
            "requires": "2.18.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-kotlin",
          "version": {
            "requires": "2.18.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-commons",
          "version": {
            "requires": "3.4.2"
          },
          "excludes": [
            {
              "group": "org.springframework",
              "module": "*"
            },
            {
              "group": "io.micrometer",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.7.2"
          }
        },
        {
          "group": "io.projectreactor.kafka",
          "module": "reactor-kafka",
          "version": {
            "requires": "1.3.23"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-core",
          "version": {
            "requires": "1.14.3"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-tracing",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-kafka-3.3.2.jar",
          "url": "spring-kafka-3.3.2.jar",
          "size": 874603,
          "sha512": "62b26f0b4511b81529a422920846c9bca455693c41550a96a5cd2382a8ff94c5974ed34deea00da8f0adb78c5c55d0a85b55cf4172f63c4aaac4f93b1d05f5d9",
          "sha256": "39aedad4ed809a5d0a81c00c543afc2d931201e02d5b3f0e8bc9d36591993282",
          "sha1": "2ab3df68531166d0f94bfc68380a9ce9dc4e9ca3",
          "md5": "75e970b44a65e740565c814558f12fd0"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.kafka",
          "name": "spring-kafka-optional",
          "version": "3.3.2"
        }
      ]
    }
  ]
}
